// React/src/App.tsx
import React, { useCallback, useEffect, useState } from 'react';
import Button from 'devextreme-react/button';
import './App.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import DataGrid, {
  DataGridTypes, Column, Editing, PatternRule, RequiredRule, StringLengthRule, Toolbar, Item,
} from 'devextreme-react/data-grid';
import notify from 'devextreme/ui/notify';
import { customers } from './data';

const pattern = /^\(\d{3}\) \d{3}-\d{4}$/i;

function App(): JSX.Element {
  let grid = React.useRef<DataGrid>(null);
  const [clicked, setClicked] = useState<Boolean>(false);
  const [changes, setChanges] = useState<DataGridTypes.DataChange[]>([]);

  const validateVisibleRows = React.useCallback(() => {
    let dataGrid = grid?.current?.instance;
    const fakeChanges = dataGrid
      ? dataGrid.getVisibleRows().map((row: DataGridTypes.Row): DataGridTypes.DataChange => ({ type: 'update', key: row.key, data: {} }))
      : [];
    // alternatively, you can use the DataGrid|option method to set a new changes array
    setChanges([...changes, ...fakeChanges]);
    setClicked(true);
  }, [changes]);

  useEffect(() => {
    if (changes.length && clicked) {
      let dataGrid = grid?.current?.instance;
      dataGrid?.repaint();
      // @ts-expect-error - getController is a private method
      dataGrid?.getController('validating').validate(true).then((result: Boolean) => {
        const message = result ? 'Validation is passed' : 'Validation is failed';
        const type = result ? 'success' : 'error';
        notify(message, type);
      });
      setClicked(false);
    }
  }, [validateVisibleRows]);

  const onChangesChange = useCallback((changes: DataGridTypes.DataChange[]): void => {
    setChanges(changes);
  }, []);

  return (
    <div className="demo-container">
      <DataGrid
        ref={grid}
        id="grid-container"
        dataSource={customers}
        keyExpr="ID"
        showBorders={true}
      >
        <Editing
          onChangesChange={onChangesChange}
          changes={changes}
          mode="batch"
          allowUpdating={true}
        />
        <Column
          dataField="CompanyName"
        >
          <RequiredRule />
        </Column>
        <Column dataField="City">
          <StringLengthRule min={4} />
        </Column>
        <Column dataField="Phone">
          <RequiredRule />
          <PatternRule
            message="Your phone must have '(555) 555-5555 format!'"
            pattern={pattern}
          />
        </Column>
        <Column dataField="Fax"></Column>
        <Column dataField="State"></Column>
        <Toolbar>
          <Item>
            <Button
              text="Validate DataGrid"
              stylingMode="outlined"
              onClick={validateVisibleRows}
            />
          </Item>
          <Item name="saveButton" />
          <Item name="revertButton" />
        </Toolbar>
      </DataGrid>
    </div>
  );
}

export default App;

// Angular/src/app/app.component.ts
import { Component, ViewChild, AfterViewChecked } from '@angular/core';
import { DxDataGridComponent, DxDataGridTypes } from 'devextreme-angular/ui/data-grid';
import notify from 'devextreme/ui/notify';
import { Customer, Service } from './app.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  providers: [Service],
})
export class AppComponent implements AfterViewChecked {
  @ViewChild(DxDataGridComponent, { static: false }) dataGrid: DxDataGridComponent | undefined;

  checked: Boolean = false;

  changes: DxDataGridTypes.DataChange[] = [];

  pattern = /^\(\d{3}\) \d{3}-\d{4}$/i;

  customers: Customer[];

  constructor(service: Service) {
    this.customers = service.getCustomers();
    this.validateVisibleRows = this.validateVisibleRows.bind(this);
  }

  validateVisibleRows(): void {
    const dataGridInstance = this?.dataGrid?.instance;
    const fakeChanges = dataGridInstance
      ? dataGridInstance.getVisibleRows().map((row: DxDataGridTypes.Row): DxDataGridTypes.DataChange => ({ type: 'update', key: row.key, data: {} }))
      : [];
    this.changes = [...this.changes, ...fakeChanges];
    this.checked = true;
  }

  ngAfterViewChecked(): void {
    if (this.changes.length && this.checked) {
      this.checked = false;
      const dataGridInstance = this?.dataGrid?.instance;
      dataGridInstance?.repaint();
      // @ts-expect-error - getController is a private method
      dataGridInstance?.getController('validating').validate(true).then((result: Boolean) => {
        const message = result ? 'Validation is passed' : 'Validation is failed';
        const type = result ? 'success' : 'error';
        notify({
          message,
          type,
          position: {
            offset: '0 50',
            at: 'bottom',
            of: '.demo-container',
          },
        });
      });
    }
  }
}

<div class="demo-container">

  <dx-data-grid
    [dataSource]="executionItems"
    keyExpr="Id"
    [repaintChangesOnly]="true"
    [showBorders]="true"
    (onSelectionChanged)="onSelectionChanged($event)"
    (onEditorPreparing)="onEditorPreparing($event)">

    <dxo-editing
      [(changes)]="changes"
      mode="cell"
      [allowUpdating]="true"
      [allowAdding]="true">
    </dxo-editing>

    <dxi-column
      dataField="IsBatch"
      caption="IsBatch"
      alignment="center"
      ></dxi-column>

    <dxi-column
      id="movements"
      dataField="Movement"
      caption="Distribué"
      dataType="number"
      alignment="center"
      cellTemplate="movementsTemplate"
      [allowEditing]="true"
    ></dxi-column>

    <div *dxTemplate="let data of 'movementsTemplate'">
      <dx-text-box
        (onValueChanged)="onValueMovementChange(data, $event)"
        [(value)]="data.value">
      </dx-text-box>
    </div>

    <dxi-column
      dataField="Lot"
      [showEditorAlways]="true"
      editCellTemplate="lotSelectionTemplate">

        <dxi-validation-rule
          message="lot requis pour ce produit"
          [validationCallback]="validateLots"
          type="custom">
        </dxi-validation-rule>

    </dxi-column>


    <div *dxTemplate="let data of 'lotSelectionTemplate'">
      <dx-select-box
        [dataSource]="data.data.LotSelection"
        displayExpr="LotNumber"
        valueExpr="LotNumber"
        [acceptCustomValue]="true"
        [value]="data.value"
        (onValueChanged)="setLotItem(data, $event)"
        (onCustomItemCreating)="addCustomItem($event, data.data)"
        placeholder="ajouter où sélectionner un lot">
      </dx-select-box>
    </div>


    <dxo-toolbar>
      <dxi-item>
        <div *dxTemplate>
          <dx-button
            text="Validate DataGrid"
            stylingMode="outlined"
            (onClick)="validateVisibleRows()"
          ></dx-button>
        </div>
      </dxi-item>
    </dxo-toolbar>
  </dx-data-grid>


</div>
